apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:hub-cluster-controller
rules:
# Allow hub to manage managedclusters
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclusters"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclusters/status"]
  verbs: ["update", "patch"]
- apiGroups: ["work.open-cluster-management.io"]
  resources: ["manifestworks"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Allow hub to get/list/watch/create/delete configmap, namespace and service account
- apiGroups: [""]
  resources: ["namespaces", "serviceaccounts", "configmaps", "events", "secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]
# allow hub to get packagemanifest to fetch the defaultChannel and currentCSV
- apiGroups: ["packages.operators.coreos.com"]
  resources: ["packagemanifests"]
  verbs: ["get", "list"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list"]
- apiGroups: ["apps.open-cluster-management.io"]
  resources: ["channels", "subscriptions", "placementrules"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

